const apiRoutes = {
  DASHBOARD: "/admin/dashboard",
  USER_LIST: "/admin/user-list",
  CONTACT_LIST: "/admin/contact-list",
  SUBSCRIBE_LIST: "/admin/subscribe-list",
  ADD_BLOG: "/admin/add-blog",
  ALL_BLOG: "/admin/get-blog",
  ADD_LANGUAGE: "/admin/add-language",
  ALL_LANGUAGE: "/admin/get-language",
  ADD_MOVIE_TYPE: "/admin/add-movieType",
  ALL_MOVIE_TYPE: "/admin/get-movieType",
  ADD_MOVIE_SHOW_TYPE: "/admin/add-movieShowType",
  ALL_MOVIE_SHOW_TYPE: "/admin/get-movieShowType",
  ADD_THEATER: "/admin/add-theater",
  ALL_THEATER: "/admin/get-theater",
  ADD_SCREEN: "/admin/add-screen",
  ALL_SCREEN: "/admin/get-screen",
  ADD_MOVIE: "/admin/add-movie",
  ALL_MOVIE: "/admin/get-movie",
  ADD_ACTOR: "/admin/add-actor",
  ALL_ACTOR: "/admin/get-actor",
  ADD_CREW: "/admin/add-crew",
  ALL_CREW: "/admin/get-crew",
};
module.exports = apiRoutes;
